@startuml
class RightLimbJointCalculator {
    + RightLimbJointCalculator(t:Transform)
    + <<override>> Refresh() : void
    + <<override>> Calc() : void
}
LimbJointCalculator <|-- RightLimbJointCalculator
@enduml
