@startuml
class CircleAnnotation {
    - _lineRenderer : LineRenderer
    - _color : Color
    - _lineWidth : float = 1.0f
    - OnEnable() : void
    - OnDisable() : void
    - OnValidate() : void
    + SetColor(color:Color) : void
    + SetLineWidth(lineWidth:float) : void
    + Draw(center:Vector3, radius:float, vertices:int) : void
    - ApplyColor(color:Color) : void
    - ApplyLineWidth(lineWidth:float) : void
}
HierarchicalAnnotation <|-- CircleAnnotation
@enduml
